[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
simple_protocol = "6yUtbQXotEAbzJBHLghordn9r3vZ8wRuCbFBxMaatVoF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/MY/KEYS/simple.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
