[package]
name = "simple-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
solana-program = "1.15.0"  # Ensure only one version is specified
spl-token = { version = "3", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib"]
