pub const SIMPLE_PUBKEY: &str = "E61fUAd1cxFES9kPckPhzwiiFMRo8ezAw7ZG5a8YD2jv";
pub const SIMPLE_MINT: &str = "DJZ2QJ9x7S4XLR7fvPouR5nZfRXqw92Y7S2BNueZmmde";

pub const RAYDIUM_POOL_WSOL_TOKEN_ACCOUNT_PUBKEY: &str =
    "EBp3owAovYaG1P9TNKfnqc4wY8FwU8iqTsA4Mprwr3JG";
pub const FLUXBEAM_POOL_WSOL_TOKEN_ACCOUNT_PUBKEY: &str =
    "9p3pKXRPz2EZZw1Wyv7uwV1MZDRwmnLT3Pv5qEt7zgdq";
